# -*- coding: utf-8 -*-
"""Blog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxSZEk1wqW45YDTeiGXVxAAa3IPttLXb
"""

import streamlit as st
from model.llama_model import getLlamaResponse

def main():
    st.title("📝 AI Blog Generator with LLaMA 2")

    topic = st.text_input("Enter Blog Topic:")
    no_of_words = st.number_input("Enter Number of Words:", min_value=50, max_value=2000, step=50)
    blog_style = st.selectbox("Choose Blog Style:", ["Professional", "Casual", "Humorous", "Technical"])

    submit = st.button("Generate")

    if submit:
        if not topic or not no_of_words:
            st.error("Please enter both topic and number of words.")
            return

        with st.spinner("Generating blog..."):
            result = getLlamaResponse(topic, no_of_words, blog_style)
            st.write(result)
            st.success("✅ DONE!")

if __name__ == '__main__':
    main()